### ISSUE TITLE
Doesn't apply to the Wiki

### ISSUE THREAD

**Issue by ThePhilStrongProject** [xthexder/wide-github#38]
Could this functionality be added to the Wiki too - tables are painful on narrow Github!

**Comment by Martii** [comment]
Will need to use it for a bit to look for regressions on other pages but:

``` css
/* Wiki */
.application-main .container-lg { 
  max-width: inherit; 
}
```
... seems to do the trick. 

NOTE: One class says experimental so it may change.
